### ISSUE TITLE
Please push your latest release to Dockerhub

### ISSUE THREAD

**Issue by nadirhamid** [rickydunlop/nodejs-ffmpeg#3]
Hello rickydunlop,

I am trying to use your Docker image locally so I can integrate FFMPEG with a node based app. however I am having issues with your Dockerhub image as it is not up to date. It seems the image on dockerhub is using an outdated node.js version.

can you please update the dockerhub image ?

thanks

**Comment by rickydunlop** [comment]
Hey Nadir, thanks for letting me know. 
I've just fixed the builds so it should be updated now. 
Let me know if there's any issues.
